Enhance build script with error handling
Add error handling and set options for build script

diff --git a/.github/workflows/cd-workflow.yml b/.github/workflows/cd-workflow.yml
--- a/.github/workflows/cd-workflow.yml
+++ b/.github/workflows/cd-workflow.yml
@@ -101,6 +101,8 @@ jobs:
         else
           export PATH=/usr/bin:$(cygpath ${SYSTEMROOT})/system32
         fi
+        set -Eeuo pipefail
+        trap 'echo "::error::Build failed at line $LINENO"' ERR
         echo PATH=$PATH
         export DESTDIR=$(realpath $(pwd)/install)
         mkdir build install
